import streamlit as st
import pandas as pd

# Page Configuration
st.set_page_config(page_title="SmartResource Analytics", page_icon="📊", layout="wide")

st.title("📊 SmartResource Environmental Analytics Dashboard")
st.markdown("This dashboard analyzes weather data to optimize future resource consumption.")

# Load the data generated by the Data Engineer
try:
    df = pd.read_csv("live_weather_forecast.csv")
    
    # Convert datetime column to proper format
    df['datetime'] = pd.to_datetime(df['datetime'])
    
    # Sidebar Metrics
    st.sidebar.header("📍 Location Details")
    st.sidebar.info("City: Algarve, Portugal")
    st.sidebar.metric(label="Total Forecast Records", value=len(df))

    # Layout: Three columns for key metrics
    col1, col2, col3 = st.columns(3)
    with col1:
        st.metric(label="🌡️ Max Temperature Forecasted", value=f"{df['temperature'].max()} °C")
    with col2:
        st.metric(label="💧 Average Humidity", value=f"{round(df['humidity'].mean(), 1)} %")
    with col3:
        st.metric(label="💨 Max Wind Speed", value=f"{df['wind_speed'].max()} m/s")

    st.markdown("---")

    # Interactive Chart: Temperature and Humidity over time
    st.subheader("📈 Environmental Metrics Over Time")
    
    # Let the user choose which metric to plot
    metric_choice = st.selectbox("Select a metric to visualize over the next few days:", ["temperature", "humidity", "wind_speed", "pressure"])
    
    # Line chart using Streamlit's native charting
    chart_data = df.set_index('datetime')[[metric_choice]]
    st.line_chart(chart_data)

    # Show raw data table if selected
    if st.checkbox("Show Raw Structured Data Table"):
        st.subheader("📋 Raw Forecast Data")
        st.dataframe(df)

except FileNotFoundError:
    st.error("❌ The file 'live_weather_forecast.csv' was not found. Please run 'data_collection.py' first to fetch the data!")